name: variant_ann
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - amply
  - annotated-types
  - appdirs
  - argparse-dataclass
  - attrs
  - blinker
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - coin-or-cbc
  - coin-or-cgl
  - coin-or-clp
  - coin-or-osi
  - coin-or-utils
  - coincbc
  - colorama
  - coloredlogs
  - conda-inject
  - configargparse
  - connection_pool
  - datrie
  - docutils
  - dpath
  - eido
  - exceptiongroup
  - flask
  - gitdb
  - gitpython
  - h2
  - hpack
  - humanfriendly
  - hyperframe
  - idna
  - immutables
  - importlib_resources
  - iniconfig
  - itsdangerous
  - jinja2
  - jsonschema
  - jsonschema-specifications
  - jupyter_core
  - libblas
  - libcblas
  - libcxx
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - liblapacke
  - libopenblas
  - libsqlite
  - libzlib
  - llvm-openmp
  - logmuse
  - markdown-it-py
  - markupsafe
  - mdurl
  - nbformat
  - ncurses
  - numpy
  - openjdk
  - openssl
  - packaging
  - pandas
  - pephubclient
  - peppy
  - pip
  - pkgutil-resolve-name
  - plac
  - platformdirs
  - pluggy
  - psutil
  - pulp
  - pycparser
  - pydantic
  - pydantic-core
  - pygments
  - pyparsing
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-tzdata
  - pytz
  - pyyaml
  - readline
  - referencing
  - requests
  - reretry
  - rich
  - rpds-py
  - setuptools
  - shellingham
  - six
  - slack-sdk
  - smart_open
  - smmap
  - snakemake
  - snakemake-interface-common
  - snakemake-interface-executor-plugins
  - snakemake-interface-report-plugins
  - snakemake-interface-storage-plugins
  - snakemake-minimal
  - snpeff
  - tabulate
  - throttler
  - tk
  - tomli
  - traitlets
  - typer
  - typer-slim
  - typer-slim-standard
  - typing-extensions
  - tzdata
  - ubiquerg
  - urllib3
  - veracitools
  - werkzeug
  - wheel
  - wrapt
  - xz
  - yaml
  - yte
  - zipp
  - zlib
  - zstandard
  - zstd
